In [1]:
import pandas as pd

In [ ]:
# pandas has two core object series, dataframe

In [2]:
# series
pd.Series((1,2,2,3),name="Age")

0    1
1    2
2    2
3    3
Name: Age, dtype: int64

In [5]:
# dataframe 
# dict 
di={"Name":["anand","mango","pen","mobile"],
    "Identity":["human","fruit","object",None]
}

df=pd.DataFrame(di)

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
df.head(2)

    Name Identity
0  anand    human
1  mango    fruit

In [8]:
df.tail(2)

     Name Identity
2     pen   object
3  mobile     None

In [16]:
df.sample()

  Name Identity
2  pen   object

In [17]:
df.head()

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     None

In [18]:
type(df["Name"])

pandas.core.series.Series

In [19]:
df[["Name","Identity"]]

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     None

In [20]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [21]:
df

   count    Name Identity
0      1   anand    human
1     10   mango    fruit
2      3     pen   object
3      2  mobile     None

In [22]:
colour = "skin","orange","blue","black"

In [23]:
df["color"] =colour

In [24]:
df["id"] =[1,2,3,4]

In [25]:
df.sample()

   count Name Identity color  id
2      3  pen   object  blue   3

In [26]:
# new df df2 id, weight
df2 = pd.DataFrame({
    'id': [1, 2, 6, 4,5],
    'weight': [55, 62, 48, 70,None]
})

print(df2)

   id  weight
0   1    55.0
1   2    62.0
2   6    48.0
3   4    70.0
4   5     NaN

In [27]:
# merge or join
pd.merge(df,df2, how="left",on="id")

   count    Name Identity   color  id  weight
0      1   anand    human    skin   1    55.0
1     10   mango    fruit  orange   2    62.0
2      3     pen   object    blue   3     NaN
3      2  mobile     None   black   4    70.0

In [30]:
pd.merge(df,df2,how='inner')  # sets

   count    Name Identity   color  id  weight
0      1   anand    human    skin   1    55.0
1     10   mango    fruit  orange   2    62.0
2      2  mobile     None   black   4    70.0