# **House Price Prediction using Machine Learning**

### **Data Loading and Preprocessing**

In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv("Data/kc_house_data.csv")

In [54]:
df.head()

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,20141013T000000,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900.0
1,6414100192,20141209T000000,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000.0
2,5631500400,20150225T000000,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000.0
3,2487200875,20141209T000000,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000.0
4,1954400510,20150218T000000,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000.0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   bedrooms       21613 non-null  int64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  int64
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_living15  21613 non-null  int64
 19  sqft_lot15     21613 non-null  int64
 20  price          21613 non-null  float64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [56]:
df.describe()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,2.161300e+04
mean,4.580302e+09,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652,5.401822e+05
std,2.876566e+09,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631,3.673622e+05
min,1.000102e+06,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,7.500000e+04
25%,2.123049e+09,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000,3.219500e+05
50%,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000,4.500000e+05
75%,7.308900e+09,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,6.450000e+05
max,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,7.700000e+06

In [57]:
df.isnull().sum()

id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
price            0
dtype: int64

In [58]:
X = df.drop('price', axis=1)
y = df['price']

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## **Simple Linear Regression**

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
X_slr = df[['sqft_living']]
y_slr = df['price']

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X_slr,
    y_slr,
    test_size=0.2,
    random_state=42
)

In [64]:
slr_model = LinearRegression()
slr_model.fit(X_train, y_train)

LinearRegression()

In [65]:
from sklearn.metrics import r2_score

In [66]:
slr_prediction = slr_model.predict(X_test)
slr_score = r2_score(y_test, slr_prediction)

In [67]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": slr_prediction
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     5.367702e+05
1      865000.0     7.689542e+05
2     1040000.0     1.012328e+06
3     1490000.0     1.233322e+06
4      711000.0     6.710453e+05

## **Multiple Linear Regression**

In [68]:
from sklearn.linear_model import LinearRegression

In [69]:
mlr_model = LinearRegression()

In [70]:
mlr_model.fit(X_train, y_train)

LinearRegression()

In [71]:
mlr_prediction = mlr_model.predict(X_test)
mlr_score = r2_score(y_test, mlr_prediction)

In [72]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": mlr_prediction
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     5.367702e+05
1      865000.0     7.689542e+05
2     1040000.0     1.012328e+06
3     1490000.0     1.233322e+06
4      711000.0     6.710453e+05

In [73]:
print("Intercept :", mlr_model.intercept_)
print("Coefficients :", mlr_model.coef_)

Intercept : -42291.12839802436
Coefficients : [279.73977846]

## **Polynomial Regression**

In [74]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [75]:
poly_reg = PolynomialFeatures(degree=2)

In [76]:
X_poly_train = poly_reg.fit_transform(X_train)
X_poly_test = poly_reg.transform(X_test)

In [77]:
poly_model = LinearRegression()

In [78]:
poly_model.fit(X_train, y_train)

LinearRegression()

In [79]:
poly_prediction = poly_model.predict(X_test)
poly_score = r2_score(y_test, poly_prediction)

In [80]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": poly_prediction
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     5.367702e+05
1      865000.0     7.689542e+05
2     1040000.0     1.012328e+06
3     1490000.0     1.233322e+06
4      711000.0     6.710453e+05

## **Support Vector Regression (SVR)**

In [81]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import r2_score

In [82]:
sc_X = StandardScaler()
sc_y = StandardScaler()

In [83]:
X_train_scaled = sc_X.fit_transform(X_train)
X_test_scaled = sc_X.transform(X_test)

In [84]:
y_train_scaled = sc_y.fit_transform(y_train.values.reshape(-1,1)).ravel()

In [85]:
svr_model = SVR(kernel='rbf')

In [86]:
svr_model.fit(X_train_scaled, y_train_scaled)

SVR()

In [87]:
prediction_scaled = svr_model.predict(X_test_scaled)
svr_prediction = sc_y.inverse_transform(prediction_scaled.reshape(-1,1)).flatten()

svr_score = r2_score(y_test, svr_prediction)

In [88]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": svr_prediction.flatten()
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     4.571731e+05
1      865000.0     6.669503e+05
2     1040000.0     9.170830e+05
3     1490000.0     1.270195e+06
4      711000.0     5.721357e+05

In [89]:
print("R2 Score :", svr_score)

R2 Score : 0.5087759105082112

## **Decision Tree Regression**

In [90]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [91]:
dt_model = DecisionTreeRegressor(random_state=42)

In [92]:
dt_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [93]:
dt_prediction = dt_model.predict(X_test)
dt_score = r2_score(y_test, dt_prediction)

In [94]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": dt_prediction
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     4.950185e+05
1      865000.0     6.851340e+05
2     1040000.0     1.110000e+06
3     1490000.0     1.038333e+06
4      711000.0     5.879995e+05

In [95]:
print("R2 Score :", dt_score)

R2 Score : 0.4377695900765557

## **Random Forest Regression**

In [96]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [97]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [98]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [99]:
rf_prediction = rf_model.predict(X_test)
rf_score = r2_score(y_test, rf_prediction)

In [100]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": rf_prediction
})

comparison.head()

   Actual Price  Predicted Price
0      365000.0     4.964223e+05
1      865000.0     6.854340e+05
2     1040000.0     1.121959e+06
3     1490000.0     1.019073e+06
4      711000.0     5.843762e+05

### **Comparing R2_score of all Algorithms**

In [101]:
print("="*55)
print("         R² SCORE COMPARISON")
print("="*55)

print(f"Simple Linear Regression     : {slr_score:.4f}")
print(f"Multiple Linear Regression   : {mlr_score:.4f}")
print(f"Polynomial Regression        : {poly_score:.4f}")
print(f"Support Vector Regression    : {svr_score:.4f}")
print(f"Decision Tree Regression     : {dt_score:.4f}")
print(f"Random Forest Regression     : {rf_score:.4f}")

print("="*55)

=======================================================
         R² SCORE COMPARISON
=======================================================
Simple Linear Regression     : 0.4941
Multiple Linear Regression   : 0.4941
Polynomial Regression        : 0.4941
Support Vector Regression    : 0.5088
Decision Tree Regression     : 0.4378
Random Forest Regression     : 0.4574
=======================================================

# **Random Forest Regression - Best Choice for House Price Prediction**

#### **Due to its robustness and high predictive performance, Random Forest is considered the best regression algorithm for this dataset.**